-- Drop TABLE "ref"."Dairas" IF EXISTS;
DROP TABLE IF EXISTS "ref"."Dairas";
-- CREATE TABLE "ref"."Dairas" IF NOT EXISTS;

CREATE TABLE IF NOT EXISTS "ref"."Dairas"(
CREATE TABLE "ref"."Dairas" (
	"Id" BIGSERIAL PRIMARY KEY,
    "RegionId" INT4 NOT null ,
    "DairaNameAr" VARCHAR(100) ,
    "DairaNameFr" VARCHAR(100),
   	"CreatedBy" INT8,
	"CreatedOn" TIMESTAMPTZ NOT NULL DEFAULT(NOW() at time zone 'utc'),
	"UpdatedBy" INT8,
	"UpdatedOn" TIMESTAMPTZ,
	"DeletedOn" TIMESTAMPTZ,
    CONSTRAINT FK_Dairas_RegionsId   FOREIGN KEY("RegionId") REFERENCES "ref"."Regions"("Id"),
    CONSTRAINT UK_Dairas             UNIQUE("RegionId","DairaNameAr","DairaNameFr")
);

-- INSERT DATA INTO TABLE "ref"."Dairas" ;
INSERT INTO ref."Dairas" ("RegionId","DairaNameAr","DairaNameFr") VALUES
	 (46,'حمام بوحجر','Hammam Bou Hadjar'),
	 (34,'الحمادية','El Hamadia'),
	 (15,'واقنون','Ouaguenoun'),
	 (22,'سفيزف','Sfisef'),
	 (42,'بواسماعيل','Bou Ismail'),
	 (5,'رأس العيون','Ras El Aioun'),
	 (36,'الطارف','El Tarf'),
	 (28,'شلال','Chellal'),
	 (15,'عزازقة','Azazga'),
	 (38,'الأزهرية','Lazharia'),
	 (26,'سيدي نعمان','Sidi Naamane'),
	 (4,'أم البواقي','Oum El Bouaghi'),
	 (25,'الخروب','El Khroub'),
	 (44,'جندل','Djendel'),
	 (36,'الذرعان','Drean'),
	 (38,'خميستي','Khemisti'),
	 (28,'سيدي عامر','Sidi Ameur'),
	 (29,'البرج','El Bordj'),
	 (18,'العوانة','El Aouana'),
	 (19,'بني عزيز','Beni Aziz'),
	 (17,'دار الشيوخ','Dar Chioukh'),
	 (14,'السوقر','Sougueur'),
	 (32,'بريزينة','Brezina'),
	 (13,'الغزوات','Ghazaouet'),
	 (19,'ماوكلان','Maoklane'),
	 (6,'صدوق','Seddouk'),
	 (41,'مداوروش','M''daourouche'),
	 (28,'خبانة','Khoubana'),
	 (11,'تاظروك','Tazrouk'),
	 (34,'عين تاغروت','Ain Taghrout'),
	 (24,'بوشقوف','Bouchegouf'),
	 (6,'برباشة','Barbacha'),
	 (22,'تنيرة','Tenira'),
	 (15,'ماكودة','Makouda'),
	 (13,'شتوان','Chetouane'),
	 (43,'سيدي مروان','Sidi Merouane'),
	 (10,'سوق الخميس','Souk El Khemis'),
	 (34,'برج الغدير','Bordj Ghedir'),
	 (44,'العامرة','El Amra'),
	 (52,'إقلي','Igli'),
	 (48,'الحمادنة','El H''madna'),
	 (42,'قوراية','Gouraya'),
	 (10,'بشلول','Bechloul'),
	 (39,'حاسي خليفة','Hassi Khalifa'),
	 (13,'بني سنوس','Beni Snous'),
	 (41,'سوق أهراس','Souk Ahras'),
	 (1,'تسابيت','Tsabit'),
	 (19,'جميلة','Djemila'),
	 (22,'سيدي بلعباس','Sidi Bel Abbes'),
	 (22,'سيدي علي بوسيدي','Sidi Ali Boussidi'),
	 (14,'رحوية','Rahouia'),
	 (1,'أدرار','Adrar'),
	 (33,'إيليزي','Illizi'),
	 (48,'غليزان','Relizane'),
	 (58,'المنيعة','El Menia'),
	 (9,'أولاد يعيش','Ouled Yaich'),
	 (29,'وادي الأبطال','Oued El Abtal'),
	 (4,'عين مليلة','Ain M''lila'),
	 (10,'عين بسام','Ain Bessem'),
	 (4,'عين ببوش','Ain Babouche'),
	 (10,'البويرة','Bouira'),
	 (45,'مكمن بن عمار','Mekmen Ben Amar'),
	 (27,'بوقيراط','Bouguirat'),
	 (26,'العزيزية','El Azizia'),
	 (31,'السانية','Es Senia'),
	 (26,'عين بوسيف','Ain Boucif'),
	 (15,'بوزقن','Bouzeguene'),
	 (7,'طولقة','Tolga'),
	 (19,'سطيف','Setif'),
	 (13,'بن سكران','Bensekrane'),
	 (10,'الحيزر','Haizer'),
	 (6,'بجاية','Bejaia'),
	 (29,'تيزي','Tizi'),
	 (50,'برج باجي مختار','Bordj Badji Mokhtar'),
	 (17,'الادريسية','El Idrissia'),
	 (12,'الونزة','Ouenza'),
	 (22,'عين البرد','Ain El Berd'),
	 (38,'لرجام','Lardjem'),
	 (36,'بوثلجة','Bouteldja'),
	 (36,'القالة','El Kala'),
	 (5,'الشمرة','Chemora'),
	 (55,'تماسين','Temacine'),
	 (5,'أولاد سي سليمان','Ouled Si Slimane'),
	 (43,'ميلة','Mila'),
	 (39,'المقرن','Magrane'),
	 (28,'أولاد سيدي ابراهيم','Ouled Sidi Brahim'),
	 (32,'بوعلام','Boualem'),
	 (48,'منداس','Mendes'),
	 (45,'المشرية','Mecheria'),
	 (48,'الرمكة','Ramka'),
	 (14,'حمادية','Hamadia'),
	 (23,'برحال','Berrahal'),
	 (34,'المنصورة','Mansourah'),
	 (36,'بوحجار','Bouhadjar'),
	 (28,'جبل مساعد','Djebel Messaad'),
	 (41,'تاورة','Taoura'),
	 (15,'ذراع بن خدة','Draa Ben Khedda'),
	 (20,'يوب','Youb'),
	 (21,'رمضان جمال','Ramdane Djamel'),
	 (14,'تيارت','Tiaret'),
	 (13,'ندرومة','Nedroma'),
	 (28,'المسيلة','M''sila'),
	 (6,'درقينة','Darguina'),
	 (29,'وادي التاغية','Oued Taria'),
	 (46,'عين تموشنت','Ain Temouchent'),
	 (4,'عين فكرون','Ain Fekroun'),
	 (55,'المقارين','Megarine'),
	 (37,'تندوف','Tindouf'),
	 (58,'المنصورة','Mansourah'),
	 (28,'مقرة','Magra'),
	 (3,'الغيشة','El Ghicha'),
	 (3,'حاسي الرمل','Hassi R''mel'),
	 (32,'البيض','El Bayadh'),
	 (19,'العلمة','El Eulma'),
	 (30,'سيدي خويلد','Sidi Khouiled'),
	 (16,'الدرارية','Draria'),
	 (12,'بئر مقدم','Bir Mokadem'),
	 (12,'أم علي','Oum Ali'),
	 (1,'فنوغيل','Fenoughil'),
	 (23,'الحجار','El Hadjar'),
	 (15,'بني يني','Benni Yenni'),
	 (51,'أولاد جلال','Ouled Djellal'),
	 (49,'تنركوك','Tinerkouk'),
	 (27,'مستغانم','Mostaganem'),
	 (14,'دحموني','Dahmouni'),
	 (25,'زيغود يوسف','Zighoud Youcef'),
	 (27,'سيدي لخضر','Sidi Lakhdar'),
	 (18,'زيامة منصورية','Ziamah Mansouriah'),
	 (13,'باب العسة','Bab El Assa'),
	 (42,'الداموس','Damous'),
	 (24,'حمام دباغ','Hammam Debagh'),
	 (32,'الأبيض سيدي الشيخ','Labiodh Sidi Cheikh'),
	 (14,'مغيلة','Meghila'),
	 (28,'بن سرور','Ben Srour'),
	 (22,'مرحوم','Marhoum'),
	 (18,'جيجل','Jijel'),
	 (5,'بوزينة','Bouzina'),
	 (56,'جانت','Djanet'),
	 (7,'مشونش','Mechouneche'),
	 (48,'المطمر','El Matmar'),
	 (34,'برج بوعريريج','Bordj Bou Arreridj'),
	 (39,'الدبيلة','Debila'),
	 (26,'تابلاط','Tablat'),
	 (52,'بني عباس','Beni Abbes'),
	 (19,'عين الكبيرة','Ain El Kebira'),
	 (26,'المدية','Medea'),
	 (35,'الثنية','Thenia'),
	 (20,'سعيدة','Saida'),
	 (28,'سيدي عيسى','Sidi Aissa'),
	 (2,'عين مران','Ain Merane'),
	 (14,'مشرع الصفا','Mechraa Sfa'),
	 (18,'الشقفة','Chekfa'),
	 (55,'الحجيرة','El-Hadjira'),
	 (29,'زهانة','Zahana'),
	 (43,'التلاغمة','Teleghma'),
	 (40,'قايس','Kais'),
	 (41,'الحدادة','Haddada'),
	 (15,'تيزي راشد','Tizi Rached'),
	 (24,'قلعة بوصبع','Guelaat Bousbaa'),
	 (44,'الروينة','Rouina'),
	 (18,'جيملة','Djimla'),
	 (31,'وهران','Oran'),
	 (12,'نقرين','Negrine'),
	 (22,'مولاي سليسن','Moulay Slissen'),
	 (6,'شميني','Chemini'),
	 (44,'مليانة','Miliana'),
	 (19,'حمام السخنة','Hammam Sokhna'),
	 (3,'قصر الحيران','Ksar El Hirane'),
	 (3,'الأغواط','Laghouat'),
	 (19,'عين ولمان','Ain Oulmene'),
	 (2,'الكريمية','El Karimia'),
	 (29,'عوف','Aouf'),
	 (18,'تاكسنة','Texenna'),
	 (6,'خراطة','Kherrata'),
	 (6,'أوقاس','Aokas'),
	 (29,'غريس','Ghriss'),
	 (11,'سيلت','Silet'),
	 (32,'شلالة','Chellala'),
	 (31,'قديل','Gdyel'),
	 (7,'أورلال','Ourlal'),
	 (48,'يلل','Yellel'),
	 (43,'القرارم قوقة','Grarem Gouga'),
	 (53,'عين صالح','In Salah'),
	 (30,'حاسي مسعود','Hassi Messaoud'),
	 (16,'بئر توتة','Birtouta'),
	 (26,'الشهبونية','Chahbounia'),
	 (14,'قصر الشلالة','Ksar Chellala'),
	 (13,'أولاد ميمون','Ouled Mimoun'),
	 (26,'سغوان','Seghouane'),
	 (10,'الهاشمية','El Hachimia'),
	 (9,'مفتاح','Meftah'),
	 (19,'قجال','Guidjel'),
	 (11,'تمنراست','Tamanrasset'),
	 (35,'بغلية','Baghlia'),
	 (21,'عين قشرة','Ain Kechra'),
	 (46,'عين الأربعاء','Ain Larbaa'),
	 (41,'سدراتة','Sedrata'),
	 (5,'إشمول','Ichemoul'),
	 (4,'الضلعة','Dhalaa'),
	 (14,'مهدية','Mahdia'),
	 (4,'قصر الصباحي','Ksar Sbahi'),
	 (2,'بني حواء','Beni Haoua'),
	 (48,'سيدي أمحمد بن علي','Sidi M''hamed Ben Ali'),
	 (18,'سيدي معروف','Sidi Marouf'),
	 (13,'عين تالوت','Ain Tellout'),
	 (15,'تيزي غنيف','Tizi-Ghenif'),
	 (36,'البسباس','Besbes'),
	 (35,'الناصرية','Naciria'),
	 (17,'حاسي بحبح','Hassi Bahbah'),
	 (2,'الشلف','Chlef'),
	 (29,'معسكر','Mascara'),
	 (34,'بئر قاصد علي','Bir Kasdali'),
	 (26,'القلب الكبير','Guelb El Kebir'),
	 (5,'تكوت','Tkout'),
	 (13,'تلمسان','Tlemcen'),
	 (57,'المغير','El Meghaier'),
	 (44,'عين الاشياخ','Ain Lechiakh'),
	 (46,'بني صاف','Beni Saf'),
	 (1,'رقان','Reggane'),
	 (9,'بوعينان','Bouinan'),
	 (16,'الدار البيضاء','Dar El Beida'),
	 (47,'المنصورة','Mansourah'),
	 (29,'المحمدية','Mohammadia'),
	 (27,'خير الدين','Kheir Eddine'),
	 (8,'بشار','Bechar'),
	 (4,'سوق نعمان','Souk Naamane'),
	 (28,'بوسعادة','Bousaada'),
	 (38,'تيسمسيلت','Tissemsilt'),
	 (43,'فرجيوة','Ferdjioua'),
	 (2,'تنس','Tenes'),
	 (24,'خزارة','Khezaras'),
	 (2,'أولاد فارس','Ouled Fares'),
	 (43,'وادي النجاء','Oued Endja'),
	 (5,'تازولت','Tazoult'),
	 (20,'أولاد ابراهيم','Ouled Brahim'),
	 (22,'بن باديس','Ben Badis'),
	 (44,'العطاف','El Attaf'),
	 (5,'سقانة','Seggana'),
	 (35,'برج منايل','Bordj Menaiel'),
	 (13,'سيدي الجيلالي','Sidi Djillali'),
	 (54,'تين زواتين','Tin Zouatine'),
	 (19,'بابور','Babor'),
	 (49,'شروين','Charouine'),
	 (8,'العبادلة','Abadla'),
	 (6,'سيدي عيش','Sidi Aich'),
	 (44,'العبادية','El Abadia'),
	 (35,'بودواو','Boudouaou'),
	 (26,'قصر البخاري','Ksar El Boukhari'),
	 (42,'أحمر العين','Ahmar El Ain'),
	 (55,'الطيبات','Taibet'),
	 (9,'بوفاريك','Boufarik'),
	 (8,'تبلبالة','Tabelbala'),
	 (42,'القليعة','Kolea'),
	 (26,'شلالة العذاورة','Chellalat El Adhaoura'),
	 (5,'تيمقاد','Timgad'),
	 (52,'الواتة','El Ouata'),
	 (13,'مرسى بن مهيدي','Marsa Ben Mehdi'),
	 (22,'سيدي لحسن','Sidi Lahcene'),
	 (2,'المرسى','El Marsa'),
	 (51,'سيدي  خالد','Sidi Khaled'),
	 (41,'المشروحة','Mechroha'),
	 (24,'وادي الزناتي','Oued Zenati'),
	 (18,'السطارة','Settara'),
	 (44,'خميس','Khemis'),
	 (24,'حمام النبايل','Hammam N''bails'),
	 (2,'بوقادير','Boukadir'),
	 (43,'شلغوم العيد','Chelghoum Laid'),
	 (23,'شطايبي','Chetaibi'),
	 (21,'تمالوس','Tamalous'),
	 (34,'برج زمورة','Bordj Zemmoura'),
	 (13,'الحناية','Hennaya'),
	 (6,'إفري أوزلاقن','Ifri Ouzellaguene'),
	 (4,'مسكيانة','Meskiana'),
	 (24,'عين مخلوف','Ain Makhlouf'),
	 (3,'قتلة سيدي سعيد','Gueltat Sidi Saad'),
	 (47,'القرارة','El Guerrara'),
	 (30,'ورقلة','Ouargla'),
	 (31,'وادي تليلات','Oued Tlelat'),
	 (24,'هيليوبوليس','Heliopolis'),
	 (48,'جديوية','Djidiouia'),
	 (28,'امجدل','Medjedel'),
	 (25,'عين عبيد','Ain Abid'),
	 (26,'أولاد عنتر','Ouled Antar'),
	 (6,'تازملت','Tazmalt'),
	 (19,'قنزات','Guenzet'),
	 (13,'فلاوسن','Fellaoucene'),
	 (2,'تاوقريت','Taougrit'),
	 (43,'الرواشد','Rouached'),
	 (16,'حسين داي','Hussein Dey'),
	 (38,'برج الأمير عبد القادر','Bordj Emir Abdelkader'),
	 (18,'العنصر','El Ancer'),
	 (22,'سيدي علي بن يوب','Sidi Ali Ben Youb'),
	 (40,'بابار','Babar'),
	 (8,'القنادسة','Kenadsa'),
	 (6,'القصر','El Kseur'),
	 (40,'بوحمامة','Bouhmama'),
	 (27,'عين تادلس','Ain Tedeles'),
	 (17,'حد الصحاري','Had Sahary'),
	 (22,'راس الماء','Ras El Ma'),
	 (3,'وادي مرة','Oued Morra'),
	 (45,'عسلة','Asla'),
	 (6,'تيشي','Tichy'),
	 (6,'أدكار','Adekar'),
	 (6,'بني معوش','Beni Maouche'),
	 (13,'منصورة','Mansourah'),
	 (42,'فوكة','Fouka'),
	 (46,'المالح','El Maleh'),
	 (39,'البياضة','Bayadha'),
	 (4,'فكيرينة','F''kirina'),
	 (13,'هنين','Honnaine'),
	 (22,'مرين','Merine'),
	 (23,'عنابة','Annaba'),
	 (19,'عموشة','Amoucha'),
	 (14,'عين كرمس','Ain Kermes'),
	 (46,'العامرية','El Amria'),
	 (5,'أريس','Arris'),
	 (26,'وزرة','Ouzera'),
	 (47,'بريان','Berriane'),
	 (39,'اميه وانسة','Mih Ouensa'),
	 (27,'عشعاشة','Achaacha'),
	 (21,'أم الطوب','Oum Toub'),
	 (9,'البليدة','Blida'),
	 (46,'عين الكيحل','Ain Kihel'),
	 (7,'سيدي عقبة','Sidi Okba'),
	 (39,'الرقيبة','Reguiba'),
	 (21,'عزابة','Azzaba'),
	 (5,'بريكة','Barika'),
	 (16,'الشراقة','Cheraga'),
	 (45,'مغرار','Moghrar'),
	 (10,'الأخضرية','Lakhdaria'),
	 (5,'المعذر','El Madher'),
	 (12,'مرسط','Morsott'),
	 (1,'أولف','Aoulef'),
	 (10,'مشد الله','M''chedallah'),
	 (3,'بريدة','Brida'),
	 (26,'البرواقية','Berrouaghia'),
	 (13,'مغنية','Maghnia'),
	 (29,'عقاز','Oggaz'),
	 (41,'أولاد إدريس','Ouled Driss'),
	 (4,'سيقوس','Sigus'),
	 (29,'تيغنيف','Tighennif'),
	 (48,'زمورة','Zemmoura'),
	 (26,'سي المحجوب','Si Mahdjoub'),
	 (48,'وادي رهيو','Oued Rhiou'),
	 (52,'أولاد خضير','Ouled Khodeir'),
	 (14,'وادي ليلي','Oued Lili'),
	 (14,'مدروسة','Medroussa'),
	 (42,'سيدي أعمر','Sidi Amar'),
	 (19,'بني ورتيلان','Beni Ourtilane'),
	 (12,'العوينات','El Aouinet'),
	 (13,'بني بوسعيد','Beni Boussaid'),
	 (33,'إن أمناس','In Amenas'),
	 (41,'المراهنة','Merahna'),
	 (42,'تيبازة','Tipaza'),
	 (12,'العقلة','El Ogla'),
	 (14,'عين الذهب','Ain Deheb'),
	 (44,'جليدة','Djelida'),
	 (38,'برج بونعامة','Bordj Bounaama'),
	 (23,'البوني','El Bouni'),
	 (21,'الحدائق','El Hadaiek'),
	 (2,'الزبوجة','Zeboudja'),
	 (25,'حامة بوزيان','Hamma Bouziane'),
	 (35,'بومرداس','Boumerdes'),
	 (47,'متليلي','Metlili'),
	 (47,'ضاية بن ضحوة','Dhayet Ben Dhahoua'),
	 (46,'ولهاصة الغرابة','Oulhassa Gheraba'),
	 (6,'أميزور','Amizour'),
	 (3,'عين ماضي','Ain Madhi'),
	 (3,'سيدي مخلوف','Sidi Makhlouf'),
	 (17,'عين الإبل','Ain El Ibel'),
	 (10,'برج أوخريص','Bordj Okhriss'),
	 (16,'بوزريعة','Bouzareah'),
	 (27,'حاسي ماماش','Hassi Mameche'),
	 (31,'بطيوة','Bethioua'),
	 (4,'عين البيضاء','Ain Beida'),
	 (29,'الحشم','Hachem'),
	 (45,'سفيسيفة','Sfissifa'),
	 (31,'بئر الجير','Bir El Djir'),
	 (16,'بئر مراد رايس','Bir Mourad Rais'),
	 (30,'البرمة','El Borma'),
	 (28,'عين الحجل','Ain El Hadjel'),
	 (15,'تيزي وزو','Tizi Ouzou'),
	 (6,'أقبو','Akbou'),
	 (32,'رقاصة','Rogassa'),
	 (32,'بوسمغون','Boussemghoun'),
	 (15,'عين الحمام','Ain El Hammam'),
	 (22,'تسالة','Tessala'),
	 (2,'وادي الفضة','Oued Fodda'),
	 (34,'رأس الوادي','Ras El Oued'),
	 (21,'سيدي مزغيش','Sidi Mezghiche'),
	 (45,'النعامة','Naama'),
	 (16,'باب الوادي','Bab El Oued'),
	 (39,'الوادي','El Oued'),
	 (5,'باتنة','Batna'),
	 (38,'ثنية الاحد','Theniet El Had'),
	 (19,'بئر العرش','Bir El Arch'),
	 (8,'تاغيت','Taghit'),
	 (39,'الرباح','Robbah'),
	 (53,'إينغر','In Ghar'),
	 (28,'أولاد دراج','Ouled Derradj'),
	 (7,'جمورة','Djemorah'),
	 (17,'بيرين','Birine'),
	 (8,'بني ونيف','Beni Ounif'),
	 (6,'سوق الإثنين','Souk El Tenine'),
	 (21,'بن عزوز','Ben Azzouz'),
	 (5,'مروانة','Merouana'),
	 (3,'أفلو','Aflou'),
	 (45,'عين الصفراء','Ain Sefra'),
	 (15,'معاتقة','Maatkas'),
	 (39,'قمار','Guemar'),
	 (21,'القل','Collo'),
	 (43,'ترعي باينان','Terrai Bainen'),
	 (4,'عين كرشة','Ain Kercha'),
	 (44,'بطحية','Bathia'),
	 (48,'عين طارق','Ain Tarek'),
	 (7,'القنطرة','El Kantara'),
	 (15,'واضية','Ouadhias'),
	 (16,'الحراش','El Harrach'),
	 (49,'أوقروت','Aougrout'),
	 (9,'بوقرة','Bougara'),
	 (6,'إغيل علي','Ighil Ali'),
	 (19,'عين أرنات','Ain Arnat'),
	 (19,'عين أزال','Ain Azel'),
	 (15,'مقلع','Mekla'),
	 (13,'الرمشي','Remchi'),
	 (35,'خميس الخشنة','Khemis El Khechna'),
	 (5,'منعة','Menaa'),
	 (44,'عين الدفلى','Ain Defla'),
	 (41,'بئر بوحوش','Bir Bouhouche'),
	 (42,'شرشال','Cherchell'),
	 (17,'الشارف','Charef'),
	 (26,'عزيز','Aziz'),
	 (15,'بني دوالة','Beni Douala'),
	 (40,'الحامة','El Hamma'),
	 (7,'زريبة الوادي','Zeribet El Oued'),
	 (48,'عمي موسى','Ammi Moussa'),
	 (31,'أرزيو','Arzew'),
	 (35,'يسر','Isser'),
	 (2,'أولاد بن عبد القادر','Ouled Ben Abdelkader'),
	 (15,'ذراع الميزان','Draa El Mizan'),
	 (28,'عين الملح','Ain El Melh'),
	 (40,'خنشلة','Khenchela'),
	 (47,'زلفانة','Zelfana'),
	 (15,'الأربعاء ناث إيراثن','Larbaa Nath Iraten'),
	 (15,'تيقزيرت','Tigzirt'),
	 (19,'حمام قرقور','Hammam Guergour'),
	 (17,'عين وسارة','Ain Oussera'),
	 (22,'مصطفى بن ابراهيم','Mostefa  Ben Brahim'),
	 (17,'الجلفة','Djelfa'),
	 (55,'تقرت','Touggourt'),
	 (17,'فيض البطمة','Faidh El Botma'),
	 (15,'إفرحونان','Iferhounene'),
	 (22,'تلاغ','Telagh'),
	 (24,'عين حساينية','Ain Hessainia'),
	 (10,'بئر غبالو','Bir Ghbalou'),
	 (16,'براقي','Baraki'),
	 (5,'عين جاسر','Ain Djasser'),
	 (49,'تيميمون','Timimoun'),
	 (5,'سريانة','Seriana'),
	 (20,'عين الحجر','Ain El Hadjar'),
	 (16,'الرويبة','Rouiba'),
	 (7,'بسكرة','Biskra'),
	 (2,'أبو الحسن','Abou El Hassane'),
	 (29,'عين فارس','Ain Fares'),
	 (15,'بوغني','Boghni'),
	 (9,'العفرون','El Affroun'),
	 (47,'بونورة','Bounoura'),
	 (21,'أولاد عطية','Ouled Attia'),
	 (31,'عين الترك','Ain Turk'),
	 (13,'صبرة','Sabra'),
	 (29,'عين فكان','Ain Fekan'),
	 (5,'عين التوتة','Ain Touta'),
	 (40,'عين الطويلة','Ain Touila'),
	 (40,'ششار','Chechar'),
	 (57,'جامعة','Djamaa'),
	 (25,'قسنطينة','Constantine'),
	 (20,'سيدي بوبكر','Sidi Boubekeur'),
	 (6,'تيمزريت','Timezrit'),
	 (38,'عماري','Ammari'),
	 (1,'زاوية كنتة','Zaouiat Kounta'),
	 (18,'الطاهير','Taher'),
	 (34,'مجانة','Medjana'),
	 (44,'برج الأمير خالد','Bordj El Emir Khaled'),
	 (26,'العمارية','El Omaria'),
	 (26,'بني سليمان','Beni Slimane'),
	 (31,'بوتليليس','Boutlelis'),
	 (42,'حجوط','Hadjout'),
	 (27,'عين نويسي','Ain Nouicy'),
	 (29,'سيق','Sig'),
	 (21,'سكيكدة','Skikda'),
	 (10,'القادرية','Kadiria'),
	 (29,'بوحنيفية','Bouhanifia'),
	 (27,'ماسرة','Mesra'),
	 (43,'عين البيضاء أحريش','Ain Beida Harriche'),
	 (43,'بوحاتم','Bouhatem'),
	 (12,'الماء الابيض','El Malabiod'),
	 (10,'سور الغزلان','Sour El Ghozlane'),
	 (28,'حمام الضلعة','Hammam Dalaa'),
	 (13,'سبدو','Sebdou'),
	 (35,'دلس','Dellys'),
	 (30,'انقوسة','N''goussa'),
	 (26,'عوامري','Ouamri'),
	 (16,'زرالدة','Zeralda'),
	 (24,'قالمة','Guelma'),
	 (21,'الحروش','El Harrouch'),
	 (12,'تبسة','Tebessa'),
	 (9,'موزاية','Mouzaia'),
	 (39,'الطالب العربي','Taleb Larbi'),
	 (26,'السواقي','Souaghi'),
	 (48,'مازونة','Mazouna'),
	 (27,'سيدي علي','Sidi Ali'),
	 (20,'الحساسنة','El Hassasna'),
	 (19,'بوعنداس','Bouandas'),
	 (40,'أولاد رشاش','Ouled Rechache'),
	 (19,'بوقاعة','Bougaa'),
	 (44,'حمام ريغة','Hammam Righa'),
	 (15,'أزفون','Azeffoun'),
	 (47,'غرداية','Ghardaia'),
	 (44,'بومدفع','Boumedfaa'),
	 (5,'ثنية العابد','Theniet El Abed'),
	 (41,'أم العظايم','Oum El Adhaim'),
	 (7,'فوغالة','Foughala'),
	 (9,'وادي العلايق','Oued El Alleug'),
	 (18,'الميلية','El Milia'),
	 (43,'تاجنانت','Tadjenanet'),
	 (9,'الأربعاء','Larbaa'),
	 (12,'الشريعة','Cheria'),
	 (23,'عين الباردة','Ain El Berda'),
	 (21,'الزيتونة','Zitouna'),
	 (34,'جعافرة','Djaafra'),
	 (12,'بئر العاتر','Bir El Ater'),
	 (15,'واسيف','Ouacif'),
	 (52,'كرزاز','Kerzaz'),
	 (32,'بوقطب','Bougtoub'),
	 (5,'نقاوس','N''gaous'),
	 (5,'الجزار','Djezzar'),
	 (8,'لحمر','Lahmar'),
	 (25,'ابن زياد','Ibn Ziad'),
	 (17,'سيدي لعجال','Sidi Laadjel'),
	 (36,'بن مهيدي','Ben M''hidi'),
	 (17,'مسعد','Messaad'),
	 (54,'عين قزام','In Guezzam'),
	 (14,'فرندة','Frenda'),
	 (43,'تسدان حدادة','Tassadane Haddada'),
	 (16,'سيدي امحمد','Sidi M''hamed'),
	 (7,'الوطاية','El Outaya'),
	 (12,'الكويف','El Kouif'),
	 (19,'صالح باي','Salah Bey')

	 ON CONFLICT ("Id") DO NOTHING;
